spring:
  application:
    name: blog-practice
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379
      ssl:
        enabled: true
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static

server:
  port: 8081

logging:
  level:
    root: INFO